apiVersion: v1
kind: Pod
metadata:
  name: samurai-test-task
spec:
  containers:
    - name: web-server
      image: eramonk/samurai_test_task:latest
      ports:
        - containerPort: 3000        
  
