apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  type: NodePort
  ports:
    - nodePort: 31313
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: postgres
